name: chat_app
description: "A new chat app Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  bloc: ^9.0.0
  bloc_provider: ^1.0.0
  cloud_firestore: ^5.5.0
  cloudinary: ^1.2.0
  conditional_builder_null_safety: ^0.0.6
  cupertino_icons: ^1.0.8
  firebase_app_check: ^0.3.1+7
  firebase_auth: ^5.3.3
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.5
  firebase_storage: ^12.3.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_local_notifications: ^18.0.1
  flutter_secure_storage: ^9.2.4
  fluttertoast: ^8.2.10
  get_it: ^8.0.2
  googleapis_auth: ^1.6.0
  hive: null
  hive_flutter: ^1.1.0
  http: ^1.2.2
  image_picker: ^1.1.2
  internet_connection_checker: ^3.0.1
  intl: ^0.20.2
  provider: ^6.1.2

dev_dependencies:
  build_runner: ^2.4.13
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/chat_icon.png"
  min_sdk_android: 21

flutter:

  uses-material-design: true

  assets:
    - assets/images/splash.png
    - assets/images/user_image.webP
    - assets/images/messaging_background.png
    - assets/images/wifi_off.gif
    - assets/keys/chat-app-e5cb1-8d448f79f16a.json
